# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\msys64\home\github\bmstu-4sem-cg\lab_05py\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from canvas import Canvas, DataTable


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(640, 10, 221, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.QTW_table = DataTable(self.gridLayoutWidget)
        self.QTW_table.setObjectName("QTW_table")
        self.QTW_table.setColumnCount(2)
        self.QTW_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.QTW_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTW_table.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.QTW_table, 5, 1, 1, 2)
        self.QPB_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QPB_clear.setFont(font)
        self.QPB_clear.setObjectName("QPB_clear")
        self.gridLayout.addWidget(self.QPB_clear, 3, 1, 1, 2)
        self.QPB_lock = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QPB_lock.setFont(font)
        self.QPB_lock.setObjectName("QPB_lock")
        self.gridLayout.addWidget(self.QPB_lock, 1, 1, 1, 2)
        self.QCB_delay = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.QCB_delay.setFont(font)
        self.QCB_delay.setObjectName("QCB_delay")
        self.gridLayout.addWidget(self.QCB_delay, 4, 1, 1, 2)
        self.QPB_paint = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QPB_paint.setFont(font)
        self.QPB_paint.setObjectName("QPB_paint")
        self.gridLayout.addWidget(self.QPB_paint, 2, 1, 1, 2)
        self.QCB_color = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QCB_color.setFont(font)
        self.QCB_color.setObjectName("QCB_color")
        self.QCB_color.addItem("")
        self.QCB_color.addItem("")
        self.QCB_color.addItem("")
        self.QCB_color.addItem("")
        self.gridLayout.addWidget(self.QCB_color, 0, 1, 1, 2)
        self.canvas = Canvas(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(10, 10, 621, 591))
        self.canvas.setObjectName("canvas")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Заполнение областей"))
        item = self.QTW_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.QTW_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        self.QPB_clear.setText(_translate("MainWindow", "Очистить холст"))
        self.QPB_lock.setText(_translate("MainWindow", "Замкнуть фигуру"))
        self.QCB_delay.setText(_translate("MainWindow", "Задержка"))
        self.QPB_paint.setText(_translate("MainWindow", "Закрасить фигуру"))
        self.QCB_color.setItemText(0, _translate("MainWindow", "Красный"))
        self.QCB_color.setItemText(1, _translate("MainWindow", "Белый(фон)"))
        self.QCB_color.setItemText(2, _translate("MainWindow", "Синий"))
        self.QCB_color.setItemText(3, _translate("MainWindow", "Черный"))
        self.canvas.setText(_translate("MainWindow", "TextLabel"))
