# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\msys64\home\github\bmstu-4sem-cg\lab_09py\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from canvas import Canvas


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(985, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(690, 200, 281, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.QPB_cut = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QPB_cut.setFont(font)
        self.QPB_cut.setObjectName("QPB_cut")
        self.gridLayout.addWidget(self.QPB_cut, 7, 0, 1, 2)
        self.QPB_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QPB_clear.setFont(font)
        self.QPB_clear.setObjectName("QPB_clear")
        self.gridLayout.addWidget(self.QPB_clear, 8, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(
            self.label_4, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.QRB_cutter = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QRB_cutter.setFont(font)
        self.QRB_cutter.setObjectName("QRB_cutter")
        self.gridLayout.addWidget(self.QRB_cutter, 2, 0, 1, 2)
        self.QRB_polygon = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QRB_polygon.setFont(font)
        self.QRB_polygon.setObjectName("QRB_polygon")
        self.gridLayout.addWidget(self.QRB_polygon, 1, 0, 1, 2)
        self.canvas = Canvas(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(10, 10, 671, 591))
        self.canvas.setObjectName("canvas")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Заполнение областей"))
        self.QPB_cut.setText(_translate("MainWindow", "Отсечь"))
        self.QPB_clear.setText(_translate("MainWindow", "Очистить холст"))
        self.label_4.setText(_translate("MainWindow", "Ввод мышкой"))
        self.QRB_cutter.setText(_translate("MainWindow", "Ввод отсекателя"))
        self.QRB_polygon.setText(_translate(
            "MainWindow", "Ввод многоугольника"))
        self.canvas.setText(_translate("MainWindow", "TextLabel"))
